name: aax2mp3-easy
version: git
summary: Easily convert .aax files to .mp3
description:  |
  Easily convert .aax files to .mp3
grade: stable
confinement: strict
base: core24
source-code: https://github.com/paladini/aax2mp3-easy
issues: https://github.com/kz6fittycent/aax2mp3-easy/issues
contact: https://github.com/kz6fittycent/aax2mp3-easy
license: MIT

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  aax2mp3-easy:
    command: bin/aax2mp3_easy.sh
    plugs:
      - network
      - home
      
parts:
  aax2mp3-easy:
    source: https://github.com/paladini/aax2mp3-easy
    source-type: git
    plugin: nil
    
  publish:
    plugin: dump
    source: .
    organize:
      "*": /bin/
